// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUbOWokea1HiKknXqkjX2c-8zdM9EMT1c',
    appId: '1:687931506020:web:302b8bfe34703bf1468e71',
    messagingSenderId: '687931506020',
    projectId: 'fluttermobile-7022f',
    authDomain: 'fluttermobile-7022f.firebaseapp.com',
    storageBucket: 'fluttermobile-7022f.appspot.com',
    measurementId: 'G-JZZ5V9PTKG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDeooAiJi263__2c03ipBD_41WuTJ6WBE8',
    appId: '1:687931506020:android:3c896ac3661f66de468e71',
    messagingSenderId: '687931506020',
    projectId: 'fluttermobile-7022f',
    storageBucket: 'fluttermobile-7022f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAJ2cr3bhqCjP5moNz17uVZtqXHY8RS1M',
    appId: '1:687931506020:ios:6cbf00a7bdede955468e71',
    messagingSenderId: '687931506020',
    projectId: 'fluttermobile-7022f',
    storageBucket: 'fluttermobile-7022f.appspot.com',
    iosBundleId: 'com.example.loginSignup',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDAJ2cr3bhqCjP5moNz17uVZtqXHY8RS1M',
    appId: '1:687931506020:ios:fa2b9d90bb290355468e71',
    messagingSenderId: '687931506020',
    projectId: 'fluttermobile-7022f',
    storageBucket: 'fluttermobile-7022f.appspot.com',
    iosBundleId: 'com.example.loginSignup.RunnerTests',
  );
}
